import "https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/button/button.js"
import "https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/dropdown/dropdown.js"
import "https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/menu/menu.js"
import "https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/menu-item/menu-item.js"
import "https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/icon/icon.js"
import "https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/input/input.js"
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/checkbox/checkbox.js';
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/icon-button/icon-button.js';
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/textarea/textarea.js';
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/card/card.js';
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/dialog/dialog.js';
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/tag/tag.js';
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/switch/switch.js';
import 'https://early.webawesome.com/webawesome@3.0.0-alpha.10/dist/components/avatar/avatar.js';

import "./button.js"
import "./dropdown.js"
import "./input.js"
import "./checkbox.js"
import "./icon-button.js"
import "./textarea.js"
import "./dialog.js"
import "./tag.js"
import "./toggle.js"
import "./avatar.js"
